name: defaultenv 
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.6.1
  - agate=1.6.0
  - agate-dbf=0.2.0
  - agate-excel=0.2.2
  - agate-sql=0.5.3
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - astor=0.7.1
  - astroid=2.0.3
  - astropy=3.0.5
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - babel=2.6.0
  - backcall=0.1.0
  - basemap=1.2.0
  - blas=1.1
  - bleach=3.0.2
  - bokeh=1.0.1
  - bottleneck=1.2.1
  - bz2file=0.98
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2018.10.15
  - cartopy=0.16.0
  - certifi=2018.10.15
  - cffi=1.11.5
  - cftime=1.0.2.1
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=0.6.1
  - colorama=0.4.0
  - configobj=5.0.6
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - csvkit=1.0.3
  - curl=7.62.0
  - cycler=0.10.0
  - cython=0.29
  - cytoolz=0.9.0.1
  - dask=0.20.0
  - dask-core=0.20.0
  - datashape=0.5.4
  - dbfread=2.0.7
  - dbus=1.13.0
  - decorator=4.3.0
  - distributed=1.24.0
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - expat=2.2.5
  - flask=1.0.2
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gast=0.2.0
  - geocoder=1.38.1
  - geographiclib=1.49
  - geopy=1.17.0
  - geos=3.6.2
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - grpcio=1.14.1
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - h5netcdf=0.6.2
  - h5py=2.8.0
  - hdf4=4.2.13
  - hdf5=1.10.3
  - heapdict=1.0.0
  - holoviews=1.10.9
  - icu=58.2
  - idna=2.7
  - imageio=2.4.1
  - imagesize=1.1.0
  - ipykernel=5.1.0
  - ipython=7.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - isodate=0.6.0
  - isort=4.3.4
  - itsdangerous=1.1.0
  - jdcal=1.4
  - jedi=0.13.1
  - jeepney=0.4
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=3.0.0a3
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=6.0.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.0
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.0
  - jupyterlab=0.35.4
  - jupyterlab_server=0.2.0
  - keras=2.2.4
  - keras-applications=1.0.4
  - keras-preprocessing=1.0.2
  - keyring=16.0.2
  - kiwisolver=1.0.1
  - krb5=1.16.2
  - lazy-object-proxy=1.3.1
  - leather=0.3.3
  - libcurl=7.62.0
  - libgfortran=3.0.0
  - libgpuarray=0.7.6
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.25.0
  - locket=0.2.0
  - lxml=4.2.5
  - mako=1.0.7
  - markdown=2.6.11
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - more-itertools=4.3.0
  - msgpack-python=0.5.6
  - multipledispatch=0.6.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - netcdf4=1.4.2
  - networkx=2.2
  - nose=1.3.7
  - notebook=5.7.0
  - numba=0.40.0
  - numpy=1.15.4
  - numpydoc=0.8.0
  - olefile=0.46
  - openblas=0.3.3
  - openpyxl=2.5.9
  - openssl=1.0.2p
  - orderedset=2.0
  - owslib=0.17.0
  - packaging=18.0
  - pandas=0.23.4
  - pandoc=2.3.1
  - pandocfilters=1.4.2
  - param=1.8.1
  - parsedatetime=2.4
  - parso=0.3.1
  - partd=0.3.9
  - patsy=0.5.1
  - pcre=8.41
  - pep8=1.7.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pluggy=0.8.0
  - proj4=4.9.3
  - prometheus_client=0.4.2
  - prompt_toolkit=2.0.7
  - protobuf=3.6.1
  - psutil=5.4.8
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.7.0
  - pycodestyle=2.4.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pyepsg=0.3.2
  - pyflakes=2.0.0
  - pygments=2.2.0
  - pygpu=0.7.6
  - pyhdf=0.9.10
  - pykdtree=1.3.1
  - pylint=2.1.1
  - pyopenssl=18.0.0
  - pyparsing=2.3.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pyresample=1.10.2
  - pyrsistent=0.14.5
  - pyshp=2.0.0
  - pysocks=1.6.8
  - pytest=3.10.0
  - pytest-arraydiff=0.2
  - pytest-astropy=0.4.0
  - pytest-doctestplus=0.1.3
  - pytest-openfiles=0.3.0
  - pytest-remotedata=0.3.1
  - python=3.6.6
  - python-crfsuite=0.9.6
  - python-dateutil=2.7.5
  - python-slugify=1.2.6
  - pytimeparse=1.1.8
  - pytz=2018.7
  - pyviz_comms=0.6.0
  - pywavelets=1.0.1
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtawesome=0.5.2
  - qtconsole=4.4.2
  - qtpy=1.5.2
  - ratelim=0.1.6
  - readline=7.0
  - requests=2.20.0
  - rope=0.10.7
  - scikit-image=0.14.1
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - secretstorage=3.1.0
  - send2trash=1.5.0
  - setuptools=40.5.0
  - shapely=1.6.4
  - sip=4.18.1
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sortedcontainers=2.0.5
  - sphinx=1.8.1
  - sphinxcontrib-websupport=1.1.0
  - spyder=3.3.1
  - spyder-kernels=0.2.6
  - sqlalchemy=1.2.13
  - sqlite=3.25.3
  - statsmodels=0.9.0
  - tblib=1.3.2
  - tensorboard=1.10.0
  - tensorflow=1.10.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - theano=1.0.3
  - toolchain=2.3.0
  - toolchain_c_linux-64=2.3.0
  - toolchain_cxx_linux-64=2.3.0
  - toolz=0.9.0
  - tornado=5.1.1
  - tqdm=4.28.1
  - traitlets=4.3.2
  - typed-ast=1.1.0
  - unidecode=1.0.22
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.32.2
  - widgetsnbextension=3.4.2
  - wrapt=1.10.11
  - xarray=0.11.0
  - xlrd=1.1.0
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - pip=18.1
  - pycurl=7.43.0.2
  - sphinxcontrib=1.0
  - tk=8.6.8
  - xz=5.2.4
  - pip:
    - coloredlogs==10.0
    - datetime-glob==1.0.7
    - f90nml==1.0.2
    - humanfriendly==4.17
    - lexery==1.1.0
    - msgpack==0.5.6
    - pyminifier==2.1
    - tzwhere==3.0.3

