name: defaultenv
channels:
  - conda-forge
  - defaults
dependencies:
  - agate=1.6.0=py36_2
  - agate-dbf=0.2.0=py36_0
  - agate-excel=0.2.1=py36_0
  - agate-sql=0.5.2=py36_0
  - alabaster=0.7.10=py36_1
  - anaconda-client=1.6.5=py_0
  - anaconda-project=0.8.2=py36_0
  - asn1crypto=0.24.0=py36_0
  - astroid=1.5.3=py36_0
  - astropy=3.0=py36_1
  - attrs=17.4.0=py_0
  - babel=2.5.3=py36_0
  - backports=1.0=py36_1
  - backports.functools_lru_cache=1.5=py36_0
  - basemap=1.1.0=py36_4
  - beautifulsoup4=4.6.0=py36_0
  - bitarray=0.8.1=py36_0
  - bkcharts=0.2=py36_0
  - blas=1.1=openblas
  - bleach=2.0.0=py_1
  - blinker=1.4=py_0
  - bokeh=0.12.13=py36_0
  - boto3=1.6.0=py_0
  - botocore=1.9.1=py_0
  - bottleneck=1.2.1=py36_1
  - bzip2=1.0.6=1
  - ca-certificates=2018.1.18=0
  - cairo=1.14.10=0
  - cartopy=0.16.0=py36_0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.2=py36_0
  - chardet=3.0.4=py36_0
  - click=6.7=py_1
  - cloudpickle=0.5.2=py_0
  - clyent=1.2.2=py36_0
  - colorama=0.3.9=py36_0
  - contextlib2=0.5.5=py36_0
  - cryptography=2.1.4=py36_0
  - csvkit=1.0.2=py36_0
  - curl=7.52.1=0
  - cycler=0.10.0=py36_0
  - cython=0.27.3=py36_0
  - cytoolz=0.8.2=py36_0
  - dask=0.17.1=py_1
  - dask-core=0.17.1=py_0
  - datashape=0.5.4=py36_0
  - dbfread=2.0.7=py36_0
  - dbus=1.10.22=0
  - decorator=4.1.2=py36_0
  - distributed=1.21.1=py36_0
  - docutils=0.14=py36_0
  - entrypoints=0.2.3=py36_1
  - et_xmlfile=1.0.1=py36_0
  - expat=2.2.5=0
  - fastcache=1.0.2=py36_0
  - flask=0.12.2=py36_0
  - flask-cors=3.0.3=py36_0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - gensim=3.3.0=py36_0
  - geopy=1.11.0=py36_0
  - geos=3.6.2=1
  - gettext=0.19.8.1=0
  - gevent=1.2.2=py36_0
  - glib=2.55.0=0
  - gmp=6.1.2=0
  - gmpy2=2.0.8=py36_1
  - graphite2=1.3.10=0
  - greenlet=0.4.13=py36_0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - h5netcdf=0.5.0=py_0
  - h5py=2.7.1=py36_2
  - harfbuzz=1.7.1=0
  - hdf4=4.2.13=0
  - hdf5=1.10.1=2
  - heapdict=1.0.0=py36_0
  - holoviews=1.9.4=py36_0
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - idna=2.6=py36_1
  - imageio=2.2.0=py36_0
  - imagesize=1.0.0=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.2.1=py36_1
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.1.2=py36_0
  - isodate=0.6.0=py_0
  - isort=4.2.15=py36_0
  - itsdangerous=0.24=py_2
  - jbig=2.1=0
  - jdcal=1.3=py36_0
  - jedi=0.11.1=py36_0
  - jinja2=2.10=py36_0
  - jmespath=0.9.3=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter=1.0.0=py36_0
  - jupyter_client=5.2.2=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.4.0=py_0
  - lazy-object-proxy=1.3.1=py36_0
  - leather=0.3.3=py36_0
  - libffi=3.2.1=3
  - libiconv=1.15=0
  - libnetcdf=4.5.0=3
  - libpng=1.6.34=0
  - libsodium=1.0.15=1
  - libtiff=4.0.9=0
  - libtool=2.4.6=0
  - libxcb=1.12=1
  - libxml2=2.9.7=0
  - libxslt=1.1.32=0
  - locket=0.2.0=py36_1
  - lxml=4.1.1=py36_0
  - lzo=2.10=0
  - markupsafe=1.0=py36_0
  - matplotlib=2.1.2=py36_0
  - mccabe=0.6.1=py36_0
  - mistune=0.8.3=py_0
  - mpc=1.0.3=4
  - mpfr=3.1.5=0
  - mpmath=1.0.0=py_0
  - msgpack-python=0.5.5=py36_0
  - multipledispatch=0.4.9=py36_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - netcdf4=1.3.1=py36_2
  - networkx=2.1=py36_0
  - nltk=3.2.5=py_0
  - nose=1.3.7=py36_2
  - notebook=5.4.0=py36_0
  - numexpr=2.6.4=py36_1
  - numpy=1.13.3=py36_blas_openblas_201
  - numpydoc=0.7.0=py36_0
  - oauthlib=2.0.6=py_0
  - odo=0.5.1=py36_0
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=7
  - openpyxl=2.5.0=py36_0
  - openssl=1.0.2n=0
  - owslib=0.16.0=py_0
  - packaging=16.8=py36_0
  - pandas=0.22.0=py36_0
  - pandoc=2.1.1=0
  - pandocfilters=1.4.1=py36_0
  - pango=1.40.14=0
  - param=1.5.1=py36_0
  - parsedatetime=2.4=py36_0
  - parso=0.1.1=py_0
  - partd=0.3.8=py36_0
  - path.py=10.3.1=py36_0
  - pathlib2=2.3.0=py36_0
  - patsy=0.5.0=py36_0
  - pcre=8.39=0
  - pep8=1.7.1=py_0
  - pexpect=4.4.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.0.0=py36_0
  - pixman=0.34.0=1
  - pluggy=0.6.0=py_0
  - ply=3.10=py36_0
  - proj4=4.9.3=5
  - prompt_toolkit=1.0.15=py36_0
  - psutil=5.4.0=py36_0
  - ptyprocess=0.5.2=py36_0
  - py=1.5.2=py_0
  - pycodestyle=2.3.1=py36_0
  - pycosat=0.6.3=py36_0
  - pycparser=2.18=py36_0
  - pycrypto=2.6.1=py36_1
  - pyepsg=0.3.2=py36_0
  - pyflakes=1.6.0=py36_0
  - pygments=2.2.0=py36_0
  - pyhdf=0.9.0=py36_2
  - pyjwt=1.5.3=py_0
  - pykdtree=1.2.2=py36_1
  - pylint=1.8.1=py36_0
  - pyodbc=4.0.17=py36_0
  - pyopenssl=17.4.0=py36_0
  - pyparsing=2.2.0=py36_0
  - pyproj=1.9.5.1=py36_0
  - pyqt=5.6.0=py36_4
  - pyresample=1.8.1=py36_0
  - pyshp=1.2.12=py_0
  - pysocks=1.6.8=py36_1
  - pytables=3.4.2=py36_7
  - pytest=3.4.1=py36_0
  - pytest-arraydiff=0.2=py_0
  - pytest-astropy=0.2.1=py_0
  - pytest-doctestplus=0.1.2=py_0
  - pytest-openfiles=0.2.0=py_0
  - pytest-remotedata=0.2.0=py_0
  - python=3.6.4=0
  - python-crfsuite=0.9.2=py36_0
  - python-dateutil=2.6.1=py36_0
  - python-slugify=1.2.4=py36_1
  - pytimeparse=1.1.7=py36_0
  - pytz=2018.3=py_0
  - pywavelets=0.5.2=py36_1
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_3
  - qt=5.6.2=7
  - qtawesome=0.4.4=py36_0
  - qtconsole=4.3.1=py36_0
  - qtpy=1.3.1=py36_0
  - readline=7.0=0
  - requests=2.18.4=py36_1
  - requests-oauthlib=0.8.0=py36_1
  - rope=0.10.7=py36_0
  - ruamel_yaml=0.11.14=py36_0
  - s3transfer=0.1.13=py36_0
  - scikit-image=0.13.1=py36_0
  - scikit-learn=0.19.1=py36_blas_openblas_201
  - scipy=1.0.0=py36_blas_openblas_201
  - seaborn=0.8.1=py36_0
  - send2trash=1.5.0=py_0
  - setuptools=38.5.1=py36_0
  - shapely=1.6.4=py36_0
  - simplegeneric=0.8.1=py36_0
  - singledispatch=3.4.0.3=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - smart_open=1.5.6=py36_1
  - snowballstemmer=1.2.1=py36_0
  - sortedcollections=0.5.3=py36_0
  - sortedcontainers=1.5.7=py36_0
  - sphinx=1.7.0=py36_0
  - sphinxcontrib-websupport=1.0.1=py36_0
  - spyder=3.2.7=py36_0
  - sqlalchemy=1.2.1=py36_0
  - sqlite=3.20.1=2
  - statsmodels=0.8.0=py36_0
  - sympy=1.1.1=py36_0
  - tblib=1.3.2=py36_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tk=8.6.7=0
  - toolz=0.8.2=py_2
  - tornado=4.5.3=py36_0
  - tqdm=4.19.5=py_0
  - traitlets=4.3.2=py36_0
  - twython=3.6.0=py36_0
  - typing=3.6.4=py36_0
  - unicodecsv=0.14.1=py36_0
  - unidecode=0.04.21=py36_0
  - unixodbc=2.3.4=1
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - werkzeug=0.14.1=py_0
  - wheel=0.30.0=py36_2
  - widgetsnbextension=3.1.4=py36_0
  - wrapt=1.10.11=py36_0
  - xarray=0.10.1=py36_0
  - xlrd=1.1.0=py_2
  - xlsxwriter=1.0.2=py_0
  - xlwt=1.3.0=py36_0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xz=5.2.3=0
  - yaml=0.1.6=0
  - zeromq=4.2.3=2
  - zict=0.1.3=py_0
  - zlib=1.2.11=0
  - _license=1.1=py36_1
  - anaconda=custom=py36_0
  - anaconda-navigator=1.6.4=py36_0
  - boto=2.48.0=py36_0
  - bz2file=0.98=py36_0
  - configobj=5.0.6=py36_0
  - get_terminal_size=1.0.0=py36_0
  - libgcc=5.2.0=0
  - libgfortran=3.0.0=1
  - llvmlite=0.20.0=py36_0
  - mkl=2017.0.3=0
  - mkl-service=1.1.2=py36_3
  - navigator-updater=0.1.0=py36_0
  - numba=0.35.0=np113py36_0
  - pip=9.0.1=py36_5
  - pycurl=7.43.0=py36_2
  - sphinxcontrib=1.0=py36_0
  - pip:
    - backports.shutil-get-terminal-size==1.0.0
    - coloredlogs==7.0
    - f90nml==0.21
    - humanfriendly==3.2
    - pyminifier==2.1
    - tables==3.4.2
    - tzwhere==3.0.3

